### PR TITLE
Transfer Orders & Stock Takes - Backend

### PR DESCRIPTION
**Pull request by Aboodchei**
## Description:

[Transfer Orders Backend Functionality](https://rubikal.atlassian.net/browse/HRS-47)
[Stock Takes Backend Functionality](https://rubikal.atlassian.net/browse/HRS-49)

## Type of change:

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing tests pass locally with my changes.

### CODE REVIEW

**Comment by Aboodchei** [comment]
I think some ( a lot, actually ) things are missing here. I worked on this with the assumption that once a transfer order is created, all items would automatically arrive, but that is not necessarily the case, and there may be partial completion. I will be closing and re-opening once I have that ready. Apologies.

**Comment by Aboodchei** [comment]
Fixed it, Transfer Order Variants now has the completed quantity. By default it is 0, and every time it is modified, it reflects in the Shopfiy stores.

**Comment by Aboodchei** [comment]
Since Transfer Orders & Stock Takes are really similar in their logic, I included them both in this pull request in order to ease development and review.

**Comment by Aboodchei** [comment]
Regarding Transactions, I did some researching and we won't need them, Rails got our backs.
The function that updates the inventory is in the `after_update` callback, and according to the [ActiveRecord::Transaction documentation](https://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), if an `after_*` callback raises an error, the save operation transaction will automatically be rolled back, so we're good

**Comment by hrdwdmrbl** [comment]
@Aboodchei great news!

**Pull request merged**
